project_id: "${CROWDIN_PROJECT_ID}"
api_token: "${CROWDIN_API_TOKEN}"
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: "/locales/source.json"
    translation: "/locales/%two_letters_code%.json"
    type: "json"
    update_option: "update_as_unapproved"
    export_only_approved: false
    skip_untranslated_strings: false
    skip_untranslated_files: false
    export_approved_only: false