/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adminCategories from "../adminCategories.js";
import type * as catalog_adapters_browserStorePageFetcher from "../catalog/adapters/browserStorePageFetcher.js";
import type * as catalog_adapters_catalogIdGenerator from "../catalog/adapters/catalogIdGenerator.js";
import type * as catalog_adapters_convexCatalogCategoryRepository from "../catalog/adapters/convexCatalogCategoryRepository.js";
import type * as catalog_adapters_convexPuzzleDefinitionRepository from "../catalog/adapters/convexPuzzleDefinitionRepository.js";
import type * as catalog_adapters_eventPublisher from "../catalog/adapters/eventPublisher.js";
import type * as catalog_adapters_firecrawlStorePageFetcher from "../catalog/adapters/firecrawlStorePageFetcher.js";
import type * as catalog_adapters_htmlFallback from "../catalog/adapters/htmlFallback.js";
import type * as catalog_adapters_mapper from "../catalog/adapters/mapper.js";
import type * as catalog_adapters_ogieRawProductPage from "../catalog/adapters/ogieRawProductPage.js";
import type * as catalog_adapters_ogieStorePageFetcher from "../catalog/adapters/ogieStorePageFetcher.js";
import type * as catalog_adapters_systemClock from "../catalog/adapters/systemClock.js";
import type * as catalog_approvePuzzleDefinition from "../catalog/approvePuzzleDefinition.js";
import type * as catalog_createCatalogCategory from "../catalog/createCatalogCategory.js";
import type * as catalog_errors from "../catalog/errors.js";
import type * as catalog_extractFromUrl from "../catalog/extractFromUrl.js";
import type * as catalog_findPuzzleByBarcode from "../catalog/findPuzzleByBarcode.js";
import type * as catalog_getAllBrands from "../catalog/getAllBrands.js";
import type * as catalog_getAllTags from "../catalog/getAllTags.js";
import type * as catalog_getPuzzleById from "../catalog/getPuzzleById.js";
import type * as catalog_getPuzzleCategories from "../catalog/getPuzzleCategories.js";
import type * as catalog_getPuzzleSuggestions from "../catalog/getPuzzleSuggestions.js";
import type * as catalog_getRecentPuzzles from "../catalog/getRecentPuzzles.js";
import type * as catalog_importCache from "../catalog/importCache.js";
import type * as catalog_importPuzzleImage from "../catalog/importPuzzleImage.js";
import type * as catalog_listAllPuzzles from "../catalog/listAllPuzzles.js";
import type * as catalog_listMyContributedPuzzles from "../catalog/listMyContributedPuzzles.js";
import type * as catalog_listPendingPuzzleDefinitions from "../catalog/listPendingPuzzleDefinitions.js";
import type * as catalog_mappers from "../catalog/mappers.js";
import type * as catalog_rejectPuzzleDefinition from "../catalog/rejectPuzzleDefinition.js";
import type * as catalog_reorderCatalogCategories from "../catalog/reorderCatalogCategories.js";
import type * as catalog_runDefinitionAction from "../catalog/runDefinitionAction.js";
import type * as catalog_setCatalogCategoryActive from "../catalog/setCatalogCategoryActive.js";
import type * as catalog_submitPuzzleDefinition from "../catalog/submitPuzzleDefinition.js";
import type * as catalog_updateCatalogCategory from "../catalog/updateCatalogCategory.js";
import type * as catalog_updatePuzzleDefinition from "../catalog/updatePuzzleDefinition.js";
import type * as contact_submitContactMessage from "../contact/submitContactMessage.js";
import type * as custody_getCopyCustodyTimeline from "../custody/getCopyCustodyTimeline.js";
import type * as custody_subscriber from "../custody/subscriber.js";
import type * as events_dispatch from "../events/dispatch.js";
import type * as events_makeEventPublisher from "../events/makeEventPublisher.js";
import type * as events_recordAndSchedule from "../events/recordAndSchedule.js";
import type * as exchange_accept from "../exchange/accept.js";
import type * as exchange_adapters_convexCopyPort from "../exchange/adapters/convexCopyPort.js";
import type * as exchange_adapters_convexExchangeRepository from "../exchange/adapters/convexExchangeRepository.js";
import type * as exchange_adapters_inProcessEventPublisher from "../exchange/adapters/inProcessEventPublisher.js";
import type * as exchange_adapters_mapper from "../exchange/adapters/mapper.js";
import type * as exchange_adapters_systemClock from "../exchange/adapters/systemClock.js";
import type * as exchange_adapters_uuidExchangeId from "../exchange/adapters/uuidExchangeId.js";
import type * as exchange_backfill from "../exchange/backfill.js";
import type * as exchange_cancel from "../exchange/cancel.js";
import type * as exchange_confirmCompletion from "../exchange/confirmCompletion.js";
import type * as exchange_decline from "../exchange/decline.js";
import type * as exchange_errors from "../exchange/errors.js";
import type * as exchange_getExchangeById from "../exchange/getExchangeById.js";
import type * as exchange_getExchangeMessages from "../exchange/getExchangeMessages.js";
import type * as exchange_getExchangeStats from "../exchange/getExchangeStats.js";
import type * as exchange_getExchangesByOwner from "../exchange/getExchangesByOwner.js";
import type * as exchange_getExchangesByRequester from "../exchange/getExchangesByRequester.js";
import type * as exchange_getUserExchanges from "../exchange/getUserExchanges.js";
import type * as exchange_propose from "../exchange/propose.js";
import type * as exchange_raiseDispute from "../exchange/raiseDispute.js";
import type * as exchange_readViews from "../exchange/readViews.js";
import type * as exchange_runAction from "../exchange/runAction.js";
import type * as exchanges from "../exchanges.js";
import type * as http from "../http.js";
import type * as identity_getCurrentUser from "../identity/getCurrentUser.js";
import type * as identity_getUserByClerkId from "../identity/getUserByClerkId.js";
import type * as identity_getUserById from "../identity/getUserById.js";
import type * as identity_getUserStats from "../identity/getUserStats.js";
import type * as identity_requireMember from "../identity/requireMember.js";
import type * as identity_searchUsers from "../identity/searchUsers.js";
import type * as identity_toMemberView from "../identity/toMemberView.js";
import type * as insights_exportUserData from "../insights/exportUserData.js";
import type * as insights_getCollectionBreakdown from "../insights/getCollectionBreakdown.js";
import type * as insights_getCommunityAvatars from "../insights/getCommunityAvatars.js";
import type * as insights_getCompletionTrends from "../insights/getCompletionTrends.js";
import type * as insights_getGlobalStats from "../insights/getGlobalStats.js";
import type * as insights_getPersonalStats from "../insights/getPersonalStats.js";
import type * as insights_getPlankPuzzles from "../insights/getPlankPuzzles.js";
import type * as insights_getRecommendations from "../insights/getRecommendations.js";
import type * as insights_getTradeActivity from "../insights/getTradeActivity.js";
import type * as insights_sampling from "../insights/sampling.js";
import type * as lib_axiom from "../lib/axiom.js";
import type * as lib_logEvent from "../lib/logEvent.js";
import type * as library_acquireCopy from "../library/acquireCopy.js";
import type * as library_adapters_circleAwareVisibilityPolicy from "../library/adapters/circleAwareVisibilityPolicy.js";
import type * as library_adapters_convexCatalogSnapshotProvider from "../library/adapters/convexCatalogSnapshotProvider.js";
import type * as library_adapters_convexCollectionRepository from "../library/adapters/convexCollectionRepository.js";
import type * as library_adapters_convexCopyRepository from "../library/adapters/convexCopyRepository.js";
import type * as library_adapters_convexCopyReservationPort from "../library/adapters/convexCopyReservationPort.js";
import type * as library_adapters_convexLoanRepository from "../library/adapters/convexLoanRepository.js";
import type * as library_adapters_convexPersonalCategoryRepository from "../library/adapters/convexPersonalCategoryRepository.js";
import type * as library_adapters_copyMapper from "../library/adapters/copyMapper.js";
import type * as library_adapters_eventPublisher from "../library/adapters/eventPublisher.js";
import type * as library_adapters_idGenerators from "../library/adapters/idGenerators.js";
import type * as library_adapters_loanMapper from "../library/adapters/loanMapper.js";
import type * as library_adapters_systemClock from "../library/adapters/systemClock.js";
import type * as library_adapters_visibilityPolicy from "../library/adapters/visibilityPolicy.js";
import type * as library_addCopyImage from "../library/addCopyImage.js";
import type * as library_addCopyToCollection from "../library/addCopyToCollection.js";
import type * as library_backfill from "../library/backfill.js";
import type * as library_browseOwnedPuzzles from "../library/browseOwnedPuzzles.js";
import type * as library_changeCopyCondition from "../library/changeCopyCondition.js";
import type * as library_circleSharedCopies from "../library/circleSharedCopies.js";
import type * as library_createCollection from "../library/createCollection.js";
import type * as library_createPersonalCategory from "../library/createPersonalCategory.js";
import type * as library_deleteCollection from "../library/deleteCollection.js";
import type * as library_deleteCopy from "../library/deleteCopy.js";
import type * as library_errors from "../library/errors.js";
import type * as library_getBorrowedLoans from "../library/getBorrowedLoans.js";
import type * as library_getCollectionById from "../library/getCollectionById.js";
import type * as library_getCollectionsForOwnedPuzzle from "../library/getCollectionsForOwnedPuzzle.js";
import type * as library_getCopyLoanHistory from "../library/getCopyLoanHistory.js";
import type * as library_getLentOutLoans from "../library/getLentOutLoans.js";
import type * as library_getOwnedPuzzleWithCollectionStatus from "../library/getOwnedPuzzleWithCollectionStatus.js";
import type * as library_getOwnedPuzzlesByOwner from "../library/getOwnedPuzzlesByOwner.js";
import type * as library_getUserCollections from "../library/getUserCollections.js";
import type * as library_loanReadViews from "../library/loanReadViews.js";
import type * as library_mappers from "../library/mappers.js";
import type * as library_openLoanOnSettlement from "../library/openLoanOnSettlement.js";
import type * as library_recallLoan from "../library/recallLoan.js";
import type * as library_removeCopyFromCollection from "../library/removeCopyFromCollection.js";
import type * as library_returnLoan from "../library/returnLoan.js";
import type * as library_transferOnSettlement from "../library/transferOnSettlement.js";
import type * as library_updateCollection from "../library/updateCollection.js";
import type * as library_updateCopyDetails from "../library/updateCopyDetails.js";
import type * as library_updateCopySharing from "../library/updateCopySharing.js";
import type * as notifications_adapters_channels_emailChannel from "../notifications/adapters/channels/emailChannel.js";
import type * as notifications_adapters_channels_inAppChannel from "../notifications/adapters/channels/inAppChannel.js";
import type * as notifications_adapters_channels_knockChannel from "../notifications/adapters/channels/knockChannel.js";
import type * as notifications_adapters_channels_pushChannel from "../notifications/adapters/channels/pushChannel.js";
import type * as notifications_adapters_convexNotificationPreferenceRepository from "../notifications/adapters/convexNotificationPreferenceRepository.js";
import type * as notifications_adapters_convexNotificationRepository from "../notifications/adapters/convexNotificationRepository.js";
import type * as notifications_adapters_idGenerators from "../notifications/adapters/idGenerators.js";
import type * as notifications_adapters_makeNotify from "../notifications/adapters/makeNotify.js";
import type * as notifications_adapters_notificationDelivery from "../notifications/adapters/notificationDelivery.js";
import type * as notifications_adapters_notificationMapper from "../notifications/adapters/notificationMapper.js";
import type * as notifications_adapters_systemClock from "../notifications/adapters/systemClock.js";
import type * as notifications_backfill from "../notifications/backfill.js";
import type * as notifications_errors from "../notifications/errors.js";
import type * as notifications_getMyPreferences from "../notifications/getMyPreferences.js";
import type * as notifications_knock from "../notifications/knock.js";
import type * as notifications_listMyNotifications from "../notifications/listMyNotifications.js";
import type * as notifications_markAllRead from "../notifications/markAllRead.js";
import type * as notifications_markNotificationRead from "../notifications/markNotificationRead.js";
import type * as notifications_subscriber from "../notifications/subscriber.js";
import type * as notifications_unreadCount from "../notifications/unreadCount.js";
import type * as notifications_updateNotificationPreference from "../notifications/updateNotificationPreference.js";
import type * as puzzles from "../puzzles.js";
import type * as reputation_adapters_convexExchangeCompletionPort from "../reputation/adapters/convexExchangeCompletionPort.js";
import type * as reputation_adapters_convexPartnerReviewRepository from "../reputation/adapters/convexPartnerReviewRepository.js";
import type * as reputation_adapters_convexReputationProfileRepository from "../reputation/adapters/convexReputationProfileRepository.js";
import type * as reputation_adapters_idGenerators from "../reputation/adapters/idGenerators.js";
import type * as reputation_adapters_inProcessEventPublisher from "../reputation/adapters/inProcessEventPublisher.js";
import type * as reputation_adapters_partnerReviewMapper from "../reputation/adapters/partnerReviewMapper.js";
import type * as reputation_adapters_systemClock from "../reputation/adapters/systemClock.js";
import type * as reputation_backfill from "../reputation/backfill.js";
import type * as reputation_errors from "../reputation/errors.js";
import type * as reputation_getMyReviewForExchange from "../reputation/getMyReviewForExchange.js";
import type * as reputation_getReputationProfile from "../reputation/getReputationProfile.js";
import type * as reputation_listReviewsForMember from "../reputation/listReviewsForMember.js";
import type * as reputation_submitPartnerReview from "../reputation/submitPartnerReview.js";
import type * as search_globalSearch from "../search/globalSearch.js";
import type * as sharing_adapters_convexCircleRepository from "../sharing/adapters/convexCircleRepository.js";
import type * as sharing_adapters_idGenerators from "../sharing/adapters/idGenerators.js";
import type * as sharing_adapters_inProcessEventPublisher from "../sharing/adapters/inProcessEventPublisher.js";
import type * as sharing_adapters_mapper from "../sharing/adapters/mapper.js";
import type * as sharing_adapters_systemClock from "../sharing/adapters/systemClock.js";
import type * as sharing_addMember from "../sharing/addMember.js";
import type * as sharing_changePermission from "../sharing/changePermission.js";
import type * as sharing_createCircle from "../sharing/createCircle.js";
import type * as sharing_errors from "../sharing/errors.js";
import type * as sharing_getCircle from "../sharing/getCircle.js";
import type * as sharing_listMyCircles from "../sharing/listMyCircles.js";
import type * as sharing_readViews from "../sharing/readViews.js";
import type * as sharing_removeMember from "../sharing/removeMember.js";
import type * as sharing_shareCopyToCircle from "../sharing/shareCopyToCircle.js";
import type * as social_adapters_convexFollowRepository from "../social/adapters/convexFollowRepository.js";
import type * as social_adapters_convexProfileRepository from "../social/adapters/convexProfileRepository.js";
import type * as social_adapters_idGenerators from "../social/adapters/idGenerators.js";
import type * as social_adapters_inProcessEventPublisher from "../social/adapters/inProcessEventPublisher.js";
import type * as social_adapters_mappers from "../social/adapters/mappers.js";
import type * as social_adapters_systemClock from "../social/adapters/systemClock.js";
import type * as social_editProfile from "../social/editProfile.js";
import type * as social_errors from "../social/errors.js";
import type * as social_followMember from "../social/followMember.js";
import type * as social_getActivityFeed from "../social/getActivityFeed.js";
import type * as social_getProfile from "../social/getProfile.js";
import type * as social_isFollowing from "../social/isFollowing.js";
import type * as social_listFollowees from "../social/listFollowees.js";
import type * as social_listFollowers from "../social/listFollowers.js";
import type * as social_readViews from "../social/readViews.js";
import type * as social_setProfileVisibility from "../social/setProfileVisibility.js";
import type * as social_unfollowMember from "../social/unfollowMember.js";
import type * as solving_adapters_completionMapper from "../solving/adapters/completionMapper.js";
import type * as solving_adapters_convexCompletionRepository from "../solving/adapters/convexCompletionRepository.js";
import type * as solving_adapters_convexGoalRepository from "../solving/adapters/convexGoalRepository.js";
import type * as solving_adapters_idGenerators from "../solving/adapters/idGenerators.js";
import type * as solving_adapters_inProcessEventPublisher from "../solving/adapters/inProcessEventPublisher.js";
import type * as solving_adapters_systemClock from "../solving/adapters/systemClock.js";
import type * as solving_backfill from "../solving/backfill.js";
import type * as solving_createGoal from "../solving/createGoal.js";
import type * as solving_editCompletion from "../solving/editCompletion.js";
import type * as solving_errors from "../solving/errors.js";
import type * as solving_finishCompletion from "../solving/finishCompletion.js";
import type * as solving_getCompletionHistory from "../solving/getCompletionHistory.js";
import type * as solving_listMyCompletions from "../solving/listMyCompletions.js";
import type * as solving_listMyGoals from "../solving/listMyGoals.js";
import type * as solving_recordCompletion from "../solving/recordCompletion.js";
import type * as solving_reviewPuzzle from "../solving/reviewPuzzle.js";
import type * as users from "../users.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  adminCategories: typeof adminCategories;
  "catalog/adapters/browserStorePageFetcher": typeof catalog_adapters_browserStorePageFetcher;
  "catalog/adapters/catalogIdGenerator": typeof catalog_adapters_catalogIdGenerator;
  "catalog/adapters/convexCatalogCategoryRepository": typeof catalog_adapters_convexCatalogCategoryRepository;
  "catalog/adapters/convexPuzzleDefinitionRepository": typeof catalog_adapters_convexPuzzleDefinitionRepository;
  "catalog/adapters/eventPublisher": typeof catalog_adapters_eventPublisher;
  "catalog/adapters/firecrawlStorePageFetcher": typeof catalog_adapters_firecrawlStorePageFetcher;
  "catalog/adapters/htmlFallback": typeof catalog_adapters_htmlFallback;
  "catalog/adapters/mapper": typeof catalog_adapters_mapper;
  "catalog/adapters/ogieRawProductPage": typeof catalog_adapters_ogieRawProductPage;
  "catalog/adapters/ogieStorePageFetcher": typeof catalog_adapters_ogieStorePageFetcher;
  "catalog/adapters/systemClock": typeof catalog_adapters_systemClock;
  "catalog/approvePuzzleDefinition": typeof catalog_approvePuzzleDefinition;
  "catalog/createCatalogCategory": typeof catalog_createCatalogCategory;
  "catalog/errors": typeof catalog_errors;
  "catalog/extractFromUrl": typeof catalog_extractFromUrl;
  "catalog/findPuzzleByBarcode": typeof catalog_findPuzzleByBarcode;
  "catalog/getAllBrands": typeof catalog_getAllBrands;
  "catalog/getAllTags": typeof catalog_getAllTags;
  "catalog/getPuzzleById": typeof catalog_getPuzzleById;
  "catalog/getPuzzleCategories": typeof catalog_getPuzzleCategories;
  "catalog/getPuzzleSuggestions": typeof catalog_getPuzzleSuggestions;
  "catalog/getRecentPuzzles": typeof catalog_getRecentPuzzles;
  "catalog/importCache": typeof catalog_importCache;
  "catalog/importPuzzleImage": typeof catalog_importPuzzleImage;
  "catalog/listAllPuzzles": typeof catalog_listAllPuzzles;
  "catalog/listMyContributedPuzzles": typeof catalog_listMyContributedPuzzles;
  "catalog/listPendingPuzzleDefinitions": typeof catalog_listPendingPuzzleDefinitions;
  "catalog/mappers": typeof catalog_mappers;
  "catalog/rejectPuzzleDefinition": typeof catalog_rejectPuzzleDefinition;
  "catalog/reorderCatalogCategories": typeof catalog_reorderCatalogCategories;
  "catalog/runDefinitionAction": typeof catalog_runDefinitionAction;
  "catalog/setCatalogCategoryActive": typeof catalog_setCatalogCategoryActive;
  "catalog/submitPuzzleDefinition": typeof catalog_submitPuzzleDefinition;
  "catalog/updateCatalogCategory": typeof catalog_updateCatalogCategory;
  "catalog/updatePuzzleDefinition": typeof catalog_updatePuzzleDefinition;
  "contact/submitContactMessage": typeof contact_submitContactMessage;
  "custody/getCopyCustodyTimeline": typeof custody_getCopyCustodyTimeline;
  "custody/subscriber": typeof custody_subscriber;
  "events/dispatch": typeof events_dispatch;
  "events/makeEventPublisher": typeof events_makeEventPublisher;
  "events/recordAndSchedule": typeof events_recordAndSchedule;
  "exchange/accept": typeof exchange_accept;
  "exchange/adapters/convexCopyPort": typeof exchange_adapters_convexCopyPort;
  "exchange/adapters/convexExchangeRepository": typeof exchange_adapters_convexExchangeRepository;
  "exchange/adapters/inProcessEventPublisher": typeof exchange_adapters_inProcessEventPublisher;
  "exchange/adapters/mapper": typeof exchange_adapters_mapper;
  "exchange/adapters/systemClock": typeof exchange_adapters_systemClock;
  "exchange/adapters/uuidExchangeId": typeof exchange_adapters_uuidExchangeId;
  "exchange/backfill": typeof exchange_backfill;
  "exchange/cancel": typeof exchange_cancel;
  "exchange/confirmCompletion": typeof exchange_confirmCompletion;
  "exchange/decline": typeof exchange_decline;
  "exchange/errors": typeof exchange_errors;
  "exchange/getExchangeById": typeof exchange_getExchangeById;
  "exchange/getExchangeMessages": typeof exchange_getExchangeMessages;
  "exchange/getExchangeStats": typeof exchange_getExchangeStats;
  "exchange/getExchangesByOwner": typeof exchange_getExchangesByOwner;
  "exchange/getExchangesByRequester": typeof exchange_getExchangesByRequester;
  "exchange/getUserExchanges": typeof exchange_getUserExchanges;
  "exchange/propose": typeof exchange_propose;
  "exchange/raiseDispute": typeof exchange_raiseDispute;
  "exchange/readViews": typeof exchange_readViews;
  "exchange/runAction": typeof exchange_runAction;
  exchanges: typeof exchanges;
  http: typeof http;
  "identity/getCurrentUser": typeof identity_getCurrentUser;
  "identity/getUserByClerkId": typeof identity_getUserByClerkId;
  "identity/getUserById": typeof identity_getUserById;
  "identity/getUserStats": typeof identity_getUserStats;
  "identity/requireMember": typeof identity_requireMember;
  "identity/searchUsers": typeof identity_searchUsers;
  "identity/toMemberView": typeof identity_toMemberView;
  "insights/exportUserData": typeof insights_exportUserData;
  "insights/getCollectionBreakdown": typeof insights_getCollectionBreakdown;
  "insights/getCommunityAvatars": typeof insights_getCommunityAvatars;
  "insights/getCompletionTrends": typeof insights_getCompletionTrends;
  "insights/getGlobalStats": typeof insights_getGlobalStats;
  "insights/getPersonalStats": typeof insights_getPersonalStats;
  "insights/getPlankPuzzles": typeof insights_getPlankPuzzles;
  "insights/getRecommendations": typeof insights_getRecommendations;
  "insights/getTradeActivity": typeof insights_getTradeActivity;
  "insights/sampling": typeof insights_sampling;
  "lib/axiom": typeof lib_axiom;
  "lib/logEvent": typeof lib_logEvent;
  "library/acquireCopy": typeof library_acquireCopy;
  "library/adapters/circleAwareVisibilityPolicy": typeof library_adapters_circleAwareVisibilityPolicy;
  "library/adapters/convexCatalogSnapshotProvider": typeof library_adapters_convexCatalogSnapshotProvider;
  "library/adapters/convexCollectionRepository": typeof library_adapters_convexCollectionRepository;
  "library/adapters/convexCopyRepository": typeof library_adapters_convexCopyRepository;
  "library/adapters/convexCopyReservationPort": typeof library_adapters_convexCopyReservationPort;
  "library/adapters/convexLoanRepository": typeof library_adapters_convexLoanRepository;
  "library/adapters/convexPersonalCategoryRepository": typeof library_adapters_convexPersonalCategoryRepository;
  "library/adapters/copyMapper": typeof library_adapters_copyMapper;
  "library/adapters/eventPublisher": typeof library_adapters_eventPublisher;
  "library/adapters/idGenerators": typeof library_adapters_idGenerators;
  "library/adapters/loanMapper": typeof library_adapters_loanMapper;
  "library/adapters/systemClock": typeof library_adapters_systemClock;
  "library/adapters/visibilityPolicy": typeof library_adapters_visibilityPolicy;
  "library/addCopyImage": typeof library_addCopyImage;
  "library/addCopyToCollection": typeof library_addCopyToCollection;
  "library/backfill": typeof library_backfill;
  "library/browseOwnedPuzzles": typeof library_browseOwnedPuzzles;
  "library/changeCopyCondition": typeof library_changeCopyCondition;
  "library/circleSharedCopies": typeof library_circleSharedCopies;
  "library/createCollection": typeof library_createCollection;
  "library/createPersonalCategory": typeof library_createPersonalCategory;
  "library/deleteCollection": typeof library_deleteCollection;
  "library/deleteCopy": typeof library_deleteCopy;
  "library/errors": typeof library_errors;
  "library/getBorrowedLoans": typeof library_getBorrowedLoans;
  "library/getCollectionById": typeof library_getCollectionById;
  "library/getCollectionsForOwnedPuzzle": typeof library_getCollectionsForOwnedPuzzle;
  "library/getCopyLoanHistory": typeof library_getCopyLoanHistory;
  "library/getLentOutLoans": typeof library_getLentOutLoans;
  "library/getOwnedPuzzleWithCollectionStatus": typeof library_getOwnedPuzzleWithCollectionStatus;
  "library/getOwnedPuzzlesByOwner": typeof library_getOwnedPuzzlesByOwner;
  "library/getUserCollections": typeof library_getUserCollections;
  "library/loanReadViews": typeof library_loanReadViews;
  "library/mappers": typeof library_mappers;
  "library/openLoanOnSettlement": typeof library_openLoanOnSettlement;
  "library/recallLoan": typeof library_recallLoan;
  "library/removeCopyFromCollection": typeof library_removeCopyFromCollection;
  "library/returnLoan": typeof library_returnLoan;
  "library/transferOnSettlement": typeof library_transferOnSettlement;
  "library/updateCollection": typeof library_updateCollection;
  "library/updateCopyDetails": typeof library_updateCopyDetails;
  "library/updateCopySharing": typeof library_updateCopySharing;
  "notifications/adapters/channels/emailChannel": typeof notifications_adapters_channels_emailChannel;
  "notifications/adapters/channels/inAppChannel": typeof notifications_adapters_channels_inAppChannel;
  "notifications/adapters/channels/knockChannel": typeof notifications_adapters_channels_knockChannel;
  "notifications/adapters/channels/pushChannel": typeof notifications_adapters_channels_pushChannel;
  "notifications/adapters/convexNotificationPreferenceRepository": typeof notifications_adapters_convexNotificationPreferenceRepository;
  "notifications/adapters/convexNotificationRepository": typeof notifications_adapters_convexNotificationRepository;
  "notifications/adapters/idGenerators": typeof notifications_adapters_idGenerators;
  "notifications/adapters/makeNotify": typeof notifications_adapters_makeNotify;
  "notifications/adapters/notificationDelivery": typeof notifications_adapters_notificationDelivery;
  "notifications/adapters/notificationMapper": typeof notifications_adapters_notificationMapper;
  "notifications/adapters/systemClock": typeof notifications_adapters_systemClock;
  "notifications/backfill": typeof notifications_backfill;
  "notifications/errors": typeof notifications_errors;
  "notifications/getMyPreferences": typeof notifications_getMyPreferences;
  "notifications/knock": typeof notifications_knock;
  "notifications/listMyNotifications": typeof notifications_listMyNotifications;
  "notifications/markAllRead": typeof notifications_markAllRead;
  "notifications/markNotificationRead": typeof notifications_markNotificationRead;
  "notifications/subscriber": typeof notifications_subscriber;
  "notifications/unreadCount": typeof notifications_unreadCount;
  "notifications/updateNotificationPreference": typeof notifications_updateNotificationPreference;
  puzzles: typeof puzzles;
  "reputation/adapters/convexExchangeCompletionPort": typeof reputation_adapters_convexExchangeCompletionPort;
  "reputation/adapters/convexPartnerReviewRepository": typeof reputation_adapters_convexPartnerReviewRepository;
  "reputation/adapters/convexReputationProfileRepository": typeof reputation_adapters_convexReputationProfileRepository;
  "reputation/adapters/idGenerators": typeof reputation_adapters_idGenerators;
  "reputation/adapters/inProcessEventPublisher": typeof reputation_adapters_inProcessEventPublisher;
  "reputation/adapters/partnerReviewMapper": typeof reputation_adapters_partnerReviewMapper;
  "reputation/adapters/systemClock": typeof reputation_adapters_systemClock;
  "reputation/backfill": typeof reputation_backfill;
  "reputation/errors": typeof reputation_errors;
  "reputation/getMyReviewForExchange": typeof reputation_getMyReviewForExchange;
  "reputation/getReputationProfile": typeof reputation_getReputationProfile;
  "reputation/listReviewsForMember": typeof reputation_listReviewsForMember;
  "reputation/submitPartnerReview": typeof reputation_submitPartnerReview;
  "search/globalSearch": typeof search_globalSearch;
  "sharing/adapters/convexCircleRepository": typeof sharing_adapters_convexCircleRepository;
  "sharing/adapters/idGenerators": typeof sharing_adapters_idGenerators;
  "sharing/adapters/inProcessEventPublisher": typeof sharing_adapters_inProcessEventPublisher;
  "sharing/adapters/mapper": typeof sharing_adapters_mapper;
  "sharing/adapters/systemClock": typeof sharing_adapters_systemClock;
  "sharing/addMember": typeof sharing_addMember;
  "sharing/changePermission": typeof sharing_changePermission;
  "sharing/createCircle": typeof sharing_createCircle;
  "sharing/errors": typeof sharing_errors;
  "sharing/getCircle": typeof sharing_getCircle;
  "sharing/listMyCircles": typeof sharing_listMyCircles;
  "sharing/readViews": typeof sharing_readViews;
  "sharing/removeMember": typeof sharing_removeMember;
  "sharing/shareCopyToCircle": typeof sharing_shareCopyToCircle;
  "social/adapters/convexFollowRepository": typeof social_adapters_convexFollowRepository;
  "social/adapters/convexProfileRepository": typeof social_adapters_convexProfileRepository;
  "social/adapters/idGenerators": typeof social_adapters_idGenerators;
  "social/adapters/inProcessEventPublisher": typeof social_adapters_inProcessEventPublisher;
  "social/adapters/mappers": typeof social_adapters_mappers;
  "social/adapters/systemClock": typeof social_adapters_systemClock;
  "social/editProfile": typeof social_editProfile;
  "social/errors": typeof social_errors;
  "social/followMember": typeof social_followMember;
  "social/getActivityFeed": typeof social_getActivityFeed;
  "social/getProfile": typeof social_getProfile;
  "social/isFollowing": typeof social_isFollowing;
  "social/listFollowees": typeof social_listFollowees;
  "social/listFollowers": typeof social_listFollowers;
  "social/readViews": typeof social_readViews;
  "social/setProfileVisibility": typeof social_setProfileVisibility;
  "social/unfollowMember": typeof social_unfollowMember;
  "solving/adapters/completionMapper": typeof solving_adapters_completionMapper;
  "solving/adapters/convexCompletionRepository": typeof solving_adapters_convexCompletionRepository;
  "solving/adapters/convexGoalRepository": typeof solving_adapters_convexGoalRepository;
  "solving/adapters/idGenerators": typeof solving_adapters_idGenerators;
  "solving/adapters/inProcessEventPublisher": typeof solving_adapters_inProcessEventPublisher;
  "solving/adapters/systemClock": typeof solving_adapters_systemClock;
  "solving/backfill": typeof solving_backfill;
  "solving/createGoal": typeof solving_createGoal;
  "solving/editCompletion": typeof solving_editCompletion;
  "solving/errors": typeof solving_errors;
  "solving/finishCompletion": typeof solving_finishCompletion;
  "solving/getCompletionHistory": typeof solving_getCompletionHistory;
  "solving/listMyCompletions": typeof solving_listMyCompletions;
  "solving/listMyGoals": typeof solving_listMyGoals;
  "solving/recordCompletion": typeof solving_recordCompletion;
  "solving/reviewPuzzle": typeof solving_reviewPuzzle;
  users: typeof users;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
